### ISSUE TITLE
App crashes when NotificationService attempts to logout user

### ISSUE THREAD

**Issue by abhijeetviswa** [crux-bphc/CMS-Android#224]
The stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: crux.bphc.cms, PID: 2525
    java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
        at io.realm.BaseRealm.checkIfValid(BaseRealm.java:442)
        at io.realm.BaseRealm.beginTransaction(BaseRealm.java:404)
        at io.realm.Realm.beginTransaction(Realm.java:145)
        at crux.bphc.cms.helper.UserUtils.logout(UserUtils.java:32)
        at crux.bphc.cms.helper.UserUtils.logoutAndClearBackStack(UserUtils.java:78)
        at crux.bphc.cms.helper.UserUtils.checkTokenValidity(UserUtils.java:72)
        at crux.bphc.cms.service.NotificationService.handleJob(NotificationService.java:154)
        at crux.bphc.cms.service.NotificationService.lambda$onStartJob$0$NotificationService(NotificationService.java:100)
        at crux.bphc.cms.service.-$$Lambda$NotificationService$ORydnftGwlDFyTciqpxulB8B32E.run(Unknown Source:4)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

This itself was caused by a domain resolution error. Should be reproducible by simply calling UserUtils.logout from `handleJob` in `NotificationService`.

**Comment by abhijeetviswa** [comment]
With the switch to push notifications, this has become irrelevant.
