### ISSUE TITLE
NPE when opening certain notifications

### ISSUE THREAD

**Issue by abhijeetviswa** [crux-bphc/CMS-Android#304]
```
2021-01-18 12:58:25.965 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: crux.bphc.cms, PID: 15642
    java.lang.RuntimeException: Unable to start activity ComponentInfo{crux.bphc.cms/crux.bphc.cms.activities.CourseDetailActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException
        at crux.bphc.cms.activities.CourseDetailActivity.resolveIntent(CourseDetailActivity.kt:62)
        at crux.bphc.cms.activities.CourseDetailActivity.onCreate(CourseDetailActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Certain notifications may not have a course id or the course may not be available locally. In such cases, the app should gracefully fetch the new app content in the MainActivity or CourseDetailActivity. 
Additionally, MainActivity should handle the `Home page` course which contains the Site News announcements.

**Comment by abhijeetviswa** [comment]
#307 partially fixed this issue.
Need to work on site notifications next.
